print('alguma coisa')
print('outra coisa')
print("alguma coisa entre outras aspas")
print("alguma coisa entre outras aspas")
print("alguma coisa entre outras aspas")
print("alguma coisa entre outras aspas")
print("alguma coisa entre outras aspas")
